"""init

Revision ID: b282cb30de91
Revises: 
Create Date: 2023-09-21 15:02:52.493304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b282cb30de91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aspects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('admin', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name=op.f('fk_friends_friend_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_friends_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('subheader', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('aspect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspects.id'], name=op.f('fk_milestones_aspect_id_aspects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_milestones_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_aspects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aspect_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspects.id'], name=op.f('fk_user_aspects_aspect_id_aspects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_aspects_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'aspect_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_aspects')
    op.drop_table('milestones')
    op.drop_table('friends')
    op.drop_table('users')
    op.drop_table('aspects')
    # ### end Alembic commands ###
